url: https://phamtom808.github.io
baseurl: /Jekyll-Iolani/

# Site settings
title: Iolani School - Research Aid (rAID)
email: dpham@mines.edu
description: Iolani School's brand new library website. 


# Team names, titles
people:
- name: Ashlyn Okamoto
  pic: 1
  position: Co-Developer


- name: Dane Pham
  pic: 2
  position: Co-Developer

#Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:title/
  handouts:
    output: true
    permalink: /handouts/:title/
  about-us:
    output: true
    permalink: /about/:title/

# Postal address 
address:
  - line: Iolani School
  - line: 563 Kamoku St
  - line: Honolulu HI, 96826

# Build settings
markdown: kramdown
permalink: pretty