url: https://phamtom808.github.io #http://127.0.0.1:4000/ 
baseurl: ""

# Site settings
title: Research Aid - r*aid
email: dpham@mines.edu
description: Iolani School's brand new library website. 
author: Iolani School
#theme: jekyll-theme-agency

# Team names, titles
people:
- name: Ashlyn Okamoto
  pic: 1
  position: Co-Developer
  bio: Ashlyn graduated from Iolani School in 2017. She is currently studying Computer Science at Portland State University and plans to pursue a career in cybersecurity.

- name: Teachers
  pic: 3
  position: (R-L) Ms.Nagoshi, Mrs. Miwa, Mrs. Okumoto
  bio: "we will fill this out later"

- name: Dane Pham
  pic: 2
  position: Co-Developer
  bio: Dane graduated from Iolani School in 2017. He is currently studying Computer Science at Colorado School of Mines and plans to pursue a career in the Air Force as a Cyberwarfare Officer.


# Postal address 
address:
  - line: Iolani School
  - line: 563 Kamoku St
  - line: Honolulu HI, 96826

# Build settings
markdown: kramdown
permalink: pretty