url: https://phamtom808.github.io
baseurl: ""

# Site settings
title: Research Aid - r*aid
email: dpham@mines.edu
description: Iolani School's brand new library website. 
author: Iolani School
theme: jekyll-theme-agency

# Team names, titles
people:
- name: Ashlyn Okamoto
  pic: 1
  position: Co-Developer


- name: Dane Pham
  pic: 2
  position: Co-Developer
  
# Postal address 
address:
  - line: Iolani School
  - line: 563 Kamoku St
  - line: Honolulu HI, 96826

# Build settings
markdown: kramdown
permalink: pretty